[package]
name = "adventofcode2020"
version = "0.1.0"
authors = ["Jörn Horstmann <git@jhorstmann.net>"]
edition = "2018"
publish = false

[dependencies]
regex = "1.4"
once_cell = "1.5"
regex-automata = "0.1.9"